#!/usr/bin/env python3
"""Auto-generate a codemap of prototype/index.html.

Extracts function definitions, constants blocks, and groups them
by proximity into logical sections. Outputs markdown to stdout
or updates the memory codemap file directly.

Usage:
    python tools/codemap.py                  # print to stdout
    python tools/codemap.py --update         # overwrite memory/project_codemap.md
    python tools/codemap.py --json           # machine-readable output
"""

import re
import sys
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "prototype" / "index.html"
CODEMAP = ROOT / "tools" / "project_codemap.md"

# Section labels assigned to functions by keyword patterns
SECTION_RULES = [
    ("Math / Noise / Terrain", r"mulberry|simplex|fbm|ridged|terrainHeight|smoothTerrain|buildTerrain|getTerrainY|getSmoothTerrain|getExactTerrain"),
    ("World Generation", r"randomizeKingdom|createPine|createBroad|createCypress|createOak|createAncient|createDead|createRock|createBuilding|createWall|createSettlement|generateSettlement"),
    ("Rendering / Lighting", r"deferred|applyLighting|lerpColor|updateBuildingLight|moonPhase|drawMoon|updateMoonShadow|getCurrentMoon"),
    ("Camera & HUD", r"updateCamera|drawAxisHud|updateTimeDisplay|project"),
    ("Path / Trampling", r"worldToCell|getTramp|getPathSpeed|trampleAt|applyPathDebug|rebuildPathWall"),
    ("Wind & Smoke", r"getWind|updateWind|updateChimneySmoke|spawnSmoke|windForSmoke|updateSmoke|hsvToColor|canopy|_canopyKey|findNearestCanopy"),
    ("Player", r"updatePlayer|resolvePlayer|updatePlayerAttack|updatePlayerStoneDelivery"),
    ("NPCs", r"createNPCMesh|spawnNPC|findNearest(?:Tree|Rock)|pickFarmSite|pickBuildSite|pickUphill|moveNPC|updateNPC|isNpcHome|findHomeBuilding|removeDestroyed|isSiteTooClose|createCornBag|createFarmMesh"),
    ("Squirrels", r"Squirrel|squirrel|plantTree|updateGrowing|getCanopyY"),
    ("Night / Combat", r"Wraith|wraith|AshenPower|GhostPower|nightMob|updateNightMob|ghostCloud|updateGhostCloud|curlNoise|initGhostBlob|_smkCell|_rebuildSmoke|_smokeNearby"),
    ("Contamination", r"contaminate|decontaminate|updateContamination|removeOneVine"),
    ("Turrets", r"[Tt]urret|[Zz]ap"),
    ("Main Loop", r"^animate$"),
    ("Debug", r"[Dd]ebug|buildCollision|buildFaceDebug|windDebug"),
]


def extract_functions(src_text: str):
    """Extract all function declarations with line numbers."""
    entries = []
    for i, line in enumerate(src_text.splitlines(), 1):
        m = re.search(r'\bfunction\s+(\w+)\s*\(', line)
        if m:
            entries.append((i, m.group(1)))
    return entries


def extract_constants(src_text: str):
    """Extract top-level const blocks (ALL_CAPS names)."""
    consts = []
    for i, line in enumerate(src_text.splitlines(), 1):
        m = re.search(r'(?:const|let)\s+([A-Z][A-Z_0-9]{2,})\s*=', line)
        if m:
            consts.append((i, m.group(1)))
    return consts


def classify(name: str) -> str:
    for label, pattern in SECTION_RULES:
        if re.search(pattern, name):
            return label
    return "Other"


def total_lines(src_text: str) -> int:
    return len(src_text.splitlines())


def build_map(src_text: str):
    funcs = extract_functions(src_text)
    consts = extract_constants(src_text)
    n_lines = total_lines(src_text)

    sections: dict[str, list[tuple[int, str]]] = {}
    for line_no, name in funcs:
        sec = classify(name)
        sections.setdefault(sec, []).append((line_no, name))

    # Add constants as their own section
    if consts:
        first = consts[0][0]
        last = consts[-1][0]
        sections.setdefault("Constants", []).insert(0, (first, f"(constants block ~{first}-{last}, {len(consts)} total)"))

    return sections, n_lines, len(funcs)


def render_markdown(sections, n_lines, n_funcs):
    lines = [
        "---",
        "name: Code Map",
        "description: Auto-generated map of all functions in prototype/index.html with line numbers",
        "type: reference",
        "---",
        "",
        f"All code in `prototype/index.html` ({n_lines} lines, {n_funcs} functions).",
        f"Auto-generated by `tools/codemap.py`.",
        "",
    ]

    # Preserve a nice section order
    order = [s for s, _ in SECTION_RULES] + ["Constants", "Other"]
    seen = set()
    for sec in order:
        if sec not in sections or sec in seen:
            continue
        seen.add(sec)
        lines.append(f"## {sec}")
        for line_no, name in sections[sec]:
            if name.startswith("("):  # meta entry like constants summary
                lines.append(f"- {name}: ~{line_no}")
            else:
                lines.append(f"- `{name}`: ~{line_no}")
        lines.append("")

    # Controls reference (static, not parseable)
    lines.extend([
        "## Controls",
        "- WASD = move, Mouse = look, LMB hold = attack",
        "- F = place turret, T = pause time, M = cycle moon",
        "- G = toggle smoke, V = wind debug, X = axis HUD, B = collision debug",
        "",
    ])

    return "\n".join(lines)


def render_json(sections, n_lines, n_funcs):
    data = {
        "file": "prototype/index.html",
        "total_lines": n_lines,
        "total_functions": n_funcs,
        "sections": {
            sec: [{"line": ln, "name": nm} for ln, nm in entries]
            for sec, entries in sections.items()
        },
    }
    return json.dumps(data, indent=2)


def main():
    src = SRC.read_text()
    sections, n_lines, n_funcs = build_map(src)

    if "--json" in sys.argv:
        print(render_json(sections, n_lines, n_funcs))
    elif "--update" in sys.argv:
        md = render_markdown(sections, n_lines, n_funcs)
        CODEMAP.parent.mkdir(parents=True, exist_ok=True)
        CODEMAP.write_text(md)
        print(f"Updated {CODEMAP} ({n_funcs} functions, {n_lines} lines)")
    else:
        print(render_markdown(sections, n_lines, n_funcs))


if __name__ == "__main__":
    main()
